# ./.github/workflows/docker_run.yml
on: 
    push:
      branches:    
        - master
#on:
#   release:
#      types: [published]

jobs:
  my-job:
    name: build_and_run
    runs-on: ubuntu-latest
    steps:
      - uses: elgohr/Publish-Docker-Github-Action@master
        name: Publish to Registry
        env:
          MY_FIRST: variableContent
          MY_SECOND: variableContent
        with:
          name: myDocker/repository
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildoptions: "--compress --force-rm"  
      - uses: actions/checkout@v1
      - name: Build Container
        run:  docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t opencelery .
      - name: Run Container on own sources as input
        run:  source ./opencelery_docker.sh ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIBRARIES_IO_TOKEN: ${{ secrets.LIBRARIES_IO_TOKEN }}
          COINBASE_TOKEN: ${{ secrets.COINBASE_TOKEN }}
          COINBASE_SECRET: ${{ secrets.COINBASE_SECRET }}
      
#      - uses: actions/upload-artifact@v1
#        with:
#          name: Billing
#          path: receipt.txt
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "./docs/"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          build-command: "sphinx-build ./sphinx/ ./"
