# ./.github/workflows/continuousselery.yml
# Use Openselery as a simple Github action on your project workflow.
# For configuration create an .openselery.yml file in your project repo.
name: openselery
on: 
    push:
      branches:
        - master

jobs:
  openselery:
    name: openselery
    runs-on: ubuntu-latest
    steps:
      # Check out the repo openselery is working on.
      - uses: actions/checkout@v1
      - name: pull openselery from dockerhub
        run: docker pull openselery/openselery
      - name: Result folder
        run: mkdir ./results
      - name: Give everyone permission to write to this folder
        run: chmod a+rw ./results
      # Run Openselery on the current folder.
      - name: Run Openselery on Sources
        run:  > 
                docker run --rm 
                --env GITHUB_TOKEN=$GITHUB_TOKEN 
                --env LIBRARIES_API_KEY=$LIBRARIES_API_KEY 
                --env COINBASE_TOKEN=$COINBASE_TOKEN 
                --env COINBASE_SECRET=$COINBASE_SECRET
                -v $PWD/:/home/selery/runningrepo/ 
                -v $PWD/results:/home/selery/results/
                openselery/openselery 
                bash -c 'python3 selery.py --directory=/home/selery/runningrepo/ --config=/home/selery/runningrepo/OPENSELERY.yml  --results_dir=/home/selery/results/' 
        # Never print
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIBRARIES_API_KEY: ${{ secrets.LIBRARIES_API_KEY }}
          COINBASE_TOKEN: ${{ secrets.COINBASE_TOKEN }}
          COINBASE_SECRET: ${{ secrets.COINBASE_SECRET }}
        # Upload the receipt file to github artifact.
      - uses: actions/upload-artifact@v1
        with:
          name: Logs_and_Billing
          path: ./results/
